name: Build PR

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: ['20']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Use variables
        run: |
          echo "repository variable : $VAR"
          echo "hello"
        env: 
          VAR: ${{ vars.SITE_DIR }}

      - name: Run npm build
        run: npm run build
        env:
          SITE_DIR: ${{ vars.SITE_DIR }}
